# prefix key
set -g prefix C-t
bind C-t send-prefix

# window sprit
bind v split-window -h
bind h split-window -v

# origin
set -g base-index 1
set -g pane-base-index 1

# cancel escape waiting
set -g escape-time 0

# set window titles
set -g set-titles on
set -g set-titles-string '#T'

# set terminal color
set -g default-terminal 'tmux-256color'
set -ga terminal-overrides ',xterm-256color:Tc'

# status bar settings
set -g status-position top

# window renumbering setting
set -g renumber-windows on

# visual notification settings
set -g visual-activity on
setw -g monitor-activity on

# key mode settings
setw -g xterm-keys on
setw -g mode-keys vi

# toggle mouse mode
setw -g mouse on
bind m setw -g mouse \; display '*** mouse mode: #{?mouse,on,off} ***'

# toggle panes synchronize mode
bind s setw -g synchronize-panes \; display '*** panes synchronize mode: #{?synchronize-panes,on,off} ***'

# config reload setting
bind r source $HOME/.tmux.conf \; display '*** configuration reloaded ***'

# powerline settings
if 'test "$(which powerline &> /dev/null; echo $?)" -eq 0 && test "$(ps x | grep powerline-daemon | grep -v grep | wc -l)" -eq 0' 'run "powerline-daemon -q"; source "/usr/lib/python3.6/site-packages/powerline/bindings/tmux/powerline.conf"'
