# prefix key
set-option -g prefix C-t
bind C-t send-prefix

# window sprit
bind v split-window -h
bind h split-window -v

# origin
set -g base-index 1
set -g pane-base-index 1

# cancel escape waiting
set -g escape-time 0

# set window titles
set -g set-titles on
set -g set-titles-string '#T'

# set terminal color
set-option -g default-terminal 'tmux-256color'

# status bar settings
set-option -g status-position top
set-option -g status-interval 1

# window renumbering setting
set-option -g renumber-windows on

# visual notification settings
set-option -g visual-activity on
set-window-option -g monitor-activity on

# key mode settings
set-window-option -g xterm-keys on
set-window-option -g mode-keys vi

# toggle mouse mode
set-window-option -g mouse on
bind m set-window-option -g mouse \; display-message '*** mouse mode: #{?mouse,on,off} ***'

# powerline settings
source '/usr/lib/python3.6/site-packages/powerline/bindings/tmux/powerline.conf'
run-shell 'powerline-daemon -g'
