"Initial settings-------------------------
set encoding=utf-8
scriptencoding utf-8

augroup MyAutoCmd
  autocmd!
augroup END


"dein scripts-----------------------------
let s:dein_dir = expand('~/.vim') . '/plugins'
let s:repo_dir = s:dein_dir . '/repos/github.com'
let s:dein_repo_dir = s:repo_dir . '/Shougo/dein.vim'

if !isdirectory(s:dein_repo_dir)
  call system('git clone https://github.com/Shougo/dein.vim ' . shellescape(s:dein_repo_dir))
endif
exec 'set runtimepath& runtimepath^=' . fnamemodify(s:dein_repo_dir, ':p')

let s:toml = s:dein_dir . '/dein.toml'
let s:lazy_toml = s:dein_dir . '/dein_lazy.toml'
let g:dein#types#git#clone_depth = 1

if dein#load_state(s:dein_dir)
  call dein#begin(s:dein_dir)

  call dein#load_toml(s:toml, { 'lazy': 0 })
  call dein#load_toml(s:lazy_toml, { 'lazy': 1 })

  call dein#end()
  call dein#save_state()
endif

if dein#check_install(['vimproc.vim'])
  call dein#install(['vimproc.vim'])
endif

if dein#check_install()
  call dein#install()
endif


"Powerline scripts------------------------
let s:pl_global_dir = '/usr/lib/python*/site-packages/powerline'
let s:pl_local_dir = s:repo_dir . '/powerline'
let s:pl_bindings_dir = '/bindings/vim'

if !isdirectory(glob(s:pl_global_dir))
  if !isdirectory(s:pl_local_dir)
    call system('git clone https://github.com/powerline/powerline ' . shellescape(s:pl_local_dir))
  endif

  let s:powerline_dir = s:pl_local_dir . '/powerline' . s:pl_bindings_dir
else
  let s:powerline_dir = s:pl_global_dir . s:pl_bindings_dir
endif
exec 'set runtimepath^=' . fnamemodify(s:powerline_dir, ':p')


"General settings-------------------------
syntax on
filetype plugin indent on

set fileencoding=utf-8
set fileencodings=utf-8,cp932,sjis,euc-jp
set switchbuf=useopen,usetab,newtab
set backspace=indent,eol,start
set helplang=ja,en
set nrformats-=octal
set virtualedit=block
set mouse=a
set ttymouse=sgr
set visualbell t_vb=
set wildignorecase
set wildmenu
set tildeop
set hidden
set autoread
set lazyredraw
set noswapfile
set nowritebackup

if has('clipboard')
  set clipboard& clipboard^=unnamedplus
endif

"UI settings------------------------------
set splitbelow
set splitright
set cursorline
set cursorcolumn
set nostartofline
set noshowmode
set showcmd
set title
set number
set ruler
set list
set listchars=tab:▸\ ,eol:↲,extends:❯,precedes:❮
set scrolloff=5
set showtabline=2
set laststatus=2


"Search settings--------------------------
set ignorecase
set smartcase
set incsearch
set hlsearch
set history=1000


"Bracket settings-------------------------
set showmatch
set matchpairs=(:),{:},[:],<:>
set matchtime=3


"Indent settings--------------------------
set autoindent
set expandtab
set tabstop=4
set shiftwidth=4

if has('breakindent')
  set breakindent
endif


"Key binding settings---------------------
let g:mapleader = ","

"Common settings
nnoremap <silent><Leader>su :w !sudo tee %<CR>
nnoremap <silent><Leader>r :source ~/.vim/vimrc<CR>
nnoremap <silent><ESC><ESC> :noh<CR>
nnoremap <silent><C-n> :new<CR>
nnoremap <silent><C-w>h :sp<CR>
nnoremap <silent><C-w>v :vsp<CR>
nnoremap <silent><S-n> :tabnew<CR>
nnoremap <silent><S-TAB> :tabp<CR>
nnoremap <silent><TAB> :tabn<CR>
nnoremap <C-w>oh :sp<Space>
nnoremap <C-w>ov :vsp<Space>
nnoremap <C-o> :o<Space>

"Cursor settings
noremap j gj
noremap k gk
noremap <S-y> y$
noremap <S-h> ^
noremap <S-j> }
noremap <S-k> {
noremap <S-l> $

"Disable confusing keys
nnoremap ZZ <Nop>
nnoremap ZQ <Nop>
nnoremap Q <Nop>

"Disable allow keys
noremap <Left> <Nop>
noremap <Down> <Nop>
noremap <Up> <Nop>
noremap <Right> <Nop>
inoremap <Left> <Nop>
inoremap <Down> <Nop>
inoremap <Up> <Nop>
inoremap <Right> <Nop>

"Window settings
nnoremap <Left> <C-w>h
nnoremap <Down> <C-w>j
nnoremap <Up> <C-w>k
nnoremap <Right> <C-w>l
nnoremap <S-Up> <C-w>+
nnoremap <S-Down> <C-w>-
nnoremap <S-Left> <C-w><
nnoremap <S-Right> <C-w>>

"Toggle options
function! Toggle_state(name)
  echohl Title
  exec 'set ' . a:name . '!'
  if eval('&' . a:name)
    echo '*** Toggled ' . a:name . ' to true ***'
  else
    echo '*** Toggled ' . a:name . ' to false ***'
  endif
  echohl None
endfunction

if has('termguicolors')
  set termguicolors
  nnoremap <silent><Leader>g :call Toggle_state('termguicolors')<CR>
endif

nnoremap <silent><Leader>n :call Toggle_state('relativenumber')<CR>
nnoremap <silent><Leader>t :call Toggle_state('expandtab')<CR>
nnoremap <silent><Leader>w :call Toggle_state('wrap')<CR>
